Repository qutip/qutip, pull requests merged in 2018-10, with the labels that each got.

#922 Fix for installing on OSX 10.14
  qutip/cy/pyxbuilder.py
  setup.py
Labels: BUG

#924 Update Travis build process
  .travis.yml
Labels: ENH, Merge ready

#902 Citation generator updated
  qutip.bib
  qutip/about.py
  qutip/cite.py
  setup.py
Labels: Merge ready

#927 change to fit with cython0.29
  qutip/control/cy_grape.pyx
  qutip/cy/br_codegen.py
  qutip/cy/br_tensor.pyx
  qutip/cy/brtools.pxd
  qutip/cy/brtools.pyx
  qutip/cy/brtools_checks.pyx
  qutip/cy/checks.pyx
  qutip/cy/codegen.py
  qutip/cy/graph_utils.pyx
  qutip/cy/heom.pyx
  qutip/cy/interpolate.pxd
  qutip/cy/interpolate.pyx
  qutip/cy/math.pxd
  qutip/cy/math.pyx
  qutip/cy/openmp/benchmark.pyx
  qutip/cy/openmp/br_omp.pxd
  qutip/cy/openmp/br_omp.pyx
  qutip/cy/openmp/omp_sparse_utils.pyx
  qutip/cy/openmp/parfuncs.pxd
  qutip/cy/openmp/parfuncs.pyx
  qutip/cy/piqs.pyx
  qutip/cy/ptrace.pyx
  qutip/cy/sparse_routines.pxi
  qutip/cy/sparse_structs.pxd
  qutip/cy/sparse_utils.pyx
  qutip/cy/spconvert.pxd
  qutip/cy/spconvert.pyx
  qutip/cy/spmatfuncs.pxd
  qutip/cy/spmatfuncs.pyx
  qutip/cy/spmath.pxd
  qutip/cy/spmath.pyx
  qutip/cy/stochastic.pyx
  qutip/tests/test_brtools.py
  qutip/tests/test_cy_structs.py
  setup.py
Labels: Merge ready
