Repository qutip/qutip, pull requests merged in 2018-06, with the labels that each got.

#870 Fix for iterative lu solve atol keyword issues
  qutip/steadystate.py
  qutip/stochastic.py
  qutip/tests/test_steadystate.py
Labels: BUG, Medium, Merge ready

#873 fix - semidefinite cvxpy Variable and Parameter
  .travis.yml
  qutip/semidefinite.py
Labels: BUG, Medium

#875 Travis CI tests update - NOMKL+OPENMP, cvx NOMKL only
  .travis.yml
Labels: Merge ready

#864 Interp fix
  qutip/cy/interpolate.pyx
Labels: BUG, Merge ready

#855 BUG: Dnorm complex casting bug
  qutip/metrics.py
Labels: BUG, Merge ready

#876 Travis CI tests - Specify blas type in conda env create
  .travis.yml
Labels: Merge ready

#879 Fixed bug that stopped simdiag working for python3
  qutip/simdiag.py
Labels: BUG

#861 PIQS module and updates
  .travis.yml
  qutip/models/__init__.py
  qutip/models/tests/__init__.py
  qutip/piqs.py
  qutip/tests/test_piqs.py
  setup.py
Labels: ENH
