Repository qutip/qutip, pull requests merged in 2019-06, with the labels that each got.

#995 Some patches for qip.Gate
  qutip/qip/circuit.py
  qutip/qip/models/circuitprocessor.py
Labels: qip

#990 dynamic args
  qutip/cy/cqobjevo.pxd
  qutip/cy/cqobjevo.pyx
  qutip/cy/cqobjevo_factor.pxd
  qutip/cy/cqobjevo_factor.pyx
  qutip/cy/openmp/cqobjevo_omp.pyx
  qutip/cy/stochastic.pyx
  qutip/floquet.py
  qutip/propagator.py
  qutip/qobjevo.py
  qutip/qobjevo_codegen.py
  qutip/stochastic.py
  qutip/superoperator.py
  qutip/tests/test_qobjevo.py
Labels: merge ready, review in progress

#969 Qobjevo solvers
  qutip/mcsolve.py
  qutip/mesolve.py
  qutip/rhs_generate.py
  qutip/sesolve.py
  qutip/tests/test_rhs_reuse.py
Labels: review in progress, review ready

#956 removed usingned int in prange
  qutip/cy/openmp/cqobjevo_omp.pyx
Labels: review in progress

#1013 nosetests segmentation fault in Metrics docstrings
  qutip/tests/test_metrics.py
Labels: merge ready

#1024 faster mcsolve postprocessing
  qutip/cy/spconvert.pyx
  qutip/cy/stochastic.pyx
  qutip/mcsolve.py
  qutip/mesolve.py
  qutip/sesolve.py
  qutip/solver.py
Labels: merge ready

#1028 Add user defined gates, MS gate and fix some bugs (replacement)
  qutip/qip/circuit.py
  qutip/qip/gates.py
  qutip/qip/models/spinchain.py
  qutip/tests/test_gates.py
  qutip/tests/test_qubitcircuit.py
Labels: review in progress
