Repository qutip/qutip, pull requests merged in 2020-04, with the labels that each got.

#1209 Add more single-qubit gates to QubitCircuit
  qutip/qip/circuit.py
  qutip/qip/operations/__init__.py
  qutip/qip/operations/gates.py
Labels: physics, qip

#1194 Make LaTeX image conversion more resilient
  qutip/qip/circuit.py
  qutip/qip/circuit_latex.py
Labels: reviewed

#1220 Add a suggestion for tests in the PR template
  .github/pull_request_template.md
Labels: micro

#1213 Prefix variable names with _ to clear Travis CI warnings
  .travis.yml
Labels: code, micro

#1218 Add test for half integer for clebsch
  qutip/tests/test_utilities.py
Labels: code, micro

#1219 Fix dtype for randint
  qutip/mcsolve.py
  qutip/stochastic.py
Labels: BUG, code, micro

#1214 Udated tests to 3.8
  .travis.yml
  qutip/parallel.py
  qutip/tests/test_mcsolve.py
Labels: ENH, code
