Repository qutip/qutip, pull requests merged in 2020-01, with the labels that each got.

#1127 Dyn args fix
  qutip/cy/cqobjevo.pyx
  qutip/cy/mcsolve.pyx
  qutip/mcsolve.py
  qutip/mesolve.py
  qutip/qobjevo.py
  qutip/qobjevo_codegen.py
  qutip/sesolve.py
  qutip/stochastic.py
  qutip/tests/test_mcsolve.py
  qutip/tests/test_mesolve.py
  qutip/tests/test_qobjevo.py
  qutip/tests/test_sesolve.py
  qutip/tests/test_stochastic_me.py
  qutip/tests/test_stochastic_se.py
Labels: code, physics, review in progress

#1153 fix dims incongruence in `propagator`
  qutip/propagator.py
  qutip/tests/test_propagator.py
Labels: physics, review ready

#1154 Faster omp bench
  qutip/__init__.py
  qutip/cy/openmp/bench_openmp.py
  qutip/testing.py
Labels: code

#929 Updated plot_fock_distribution
  qutip/visualization.py
Labels: physics, review in progress

#1131 Migrating from nose to pytest
  .gitignore
  .travis.yml
  qutip/qobjevo_codegen.py
  qutip/testing.py
  qutip/tests/test_control_pulseoptim.py
Labels: code

#1098 Enhancement nonsquare superopreps
  qutip/dimensions.py
  qutip/qobj.py
  qutip/superop_reps.py
  qutip/superoperator.py
  qutip/tests/test_qobj.py
  qutip/tests/test_superop_reps.py
  qutip/tests/test_superoper.py
Labels: ENH, physics, review in progress, review ready

#1066 Lattice Models in QuTiP: 1d Lattices: GSoC 2019
  qutip/__init__.py
  qutip/lattice.py
  qutip/tests/test_lattice.py
  qutip/topology.py
Labels: physics

#1151 Marked test
  qutip/testing.py
  qutip/tests/test_brmesolve_td.py
  qutip/tests/test_correlation.py
  qutip/tests/test_interpolate.py
  qutip/tests/test_mcsolve.py
  qutip/tests/test_qobjevo.py
  qutip/tests/test_spmath.py
  qutip/tests/test_stochastic_me.py
  qutip/tests/test_stochastic_se.py
  qutip/tests/test_wigner.py
Labels: code, review in progress

#1159 Implicit tensor product for qeye, qzero and basis.
  qutip/operators.py
  qutip/states.py
  qutip/tests/test_operators.py
  qutip/tests/test_states.py
Labels: code, physics

#1164 Move tests to pytest
  qutip/tests/test_basis_transformation.py
  qutip/tests/test_brmesolve.py
  qutip/tests/test_brmesolve_td.py
  qutip/tests/test_brtools.py
Labels: ENH, code
